apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-rails-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rails-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: shanmicheal25/k8s-rails-ruby2.5:1.1.0
        ports:
        - containerPort: 3000